### PR TITLE
Added TOR support

### PR DESCRIPTION
**Pull request by Techno-Fox**
This allows the module to connect to IRC using TOR.

### CODE REVIEW

**Review by dom96 — CHANGES_REQUESTED** [review]
This is really cool. But I have a couple of problems with it:

* Why fork @FedericoCeratto's library and relicense it?
* I don't want IRC to depend on torim, especially when it's GPL. That would make this library GPL.
* I really wish Nim supported extending sockets so that you could just define your own socket implementation instead of having to modify the existing code.

**Comment by Techno-Fox** [comment]
Just read all of GPL. My bad. It's normaly what I use as a default.

**Comment by Techno-Fox** [comment]
And I forked it, because somethings broke with trying to implement it. Also added some more function to help in the future.

**Comment by KittyTechnoProgrammer** [comment]
All right. Anything else?

**Comment by FedericoCeratto** [comment]
@KittyTechnoProgrammer I'm happy to review https://github.com/FedericoCeratto/nim-tor/pull/4 and merge future improvements

**Comment by Techno-Fox** [comment]
Nice. Want me to send another pull request

**Comment by Techno-Fox** [comment]
you can now use normal tor. Anything else

**Comment by dom96** [comment]
Yeah, this adds a hard dependency on `tor`. I don't really want to merge this because it will add a hard dependency on that package, and make maintenance harder.

**Comment by Techno-Fox** [comment]
Maintenance. As in updating?.  Yea I see how that would be harder. However, I assume copy pasting all of tor.nim into irc.nim wouldn't be the best idea. Do you have any suggestions?

**Comment by dom96** [comment]
What might be preferable is to create a proxy that you can then connect the IRC bot through. Depends on your needs though.

**Comment by Techno-Fox** [comment]
I guess that could work. However would that work for TOR. I haven't looked into how tor works all the way, but I'm sure it's not the same as just connecting to a normal proxyserver.

**Comment by Techno-Fox** [comment]
Could just create a package call torirc (or something else, 'cause I'm not the best at names), specificly for connecting to tor IRCs

**Comment by FedericoCeratto** [comment]
The tor daemon already provides a SOCKS proxy. Applications with SOCKS support can use that.

(BTW it's written Tor not TOR :) )

**Comment by Techno-Fox** [comment]
Is it like a normal proxy? As in could just connect and boom you've got Tor? If that's the case, then why not just add a proxy option in irc.nim? Would that be a valid method?

**Comment by dom96** [comment]
Closing in favour of https://github.com/nim-lang/irc/pull/21

**Pull request closed without merging**
