### PR TITLE
preserve the message verb for later parsing if needed

### PR DESCRIPTION
**Pull request by Heartmender**

### CODE REVIEW

**Comment by dom96** [comment]
What is the purpose of this? `cmd` stores this already, and parsed too.

**Comment by Heartmender** [comment]
There are verbs that the ircd can send that you do not have in your enum. I would prefer to have the verbs directly available so I can do more complicated parsing of advanced features.

**Comment by dom96** [comment]
What verbs are those? I would prefer if you add those to the enum not conflate the meaning of 'numeric'.

**Comment by fowlmouth** [comment]
@dom96 without this patch you have to parse the raw message retrieve the actual numeric value.

```
[EvMsg
cmd = MNumeric,
nick = 0x7fce96623dc0"",
user = nil,
host = nil,
servername = 0x7fce96622360"barjavel.freenode.net",
numeric = 0x7fce96623e60"366",
params = 0x7fce96630110[0x7fce96623eb0"botfowl", 0x7fce966334a0"#fancyfeast", 0x7fce966222b8"End of /NAMES list."],
origin = 0x7fce96623ed8"botfowl",
raw = 0x7fce96637188":barjavel.freenode.net 366 botfowl #fancyfeast :End of /NAMES list.",
timestamp = 1431630282]
```

**Comment by dom96** [comment]
No, you don't. Numeric is set for MNumeric's.

https://github.com/nim-lang/irc/blob/master/src/irc.nim#L232

**Comment by dom96** [comment]
I'm afraid I'm going to need to revert this.

**Pull request merged**
